version: '3'
services:
    portfolio:
        image: my-portfolio
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: my_portfolio
        ports: 
            - 3010:3010
        restart: unless-stopped
        entrypoint:
          [
            'npm'
          ]
        command:
          [
            'start'
          ]
        volumes:
          - .:/home/node/sibi